
def load_mysterious_list():
    return [
        'Goblet of Fire',
        'Unicorn',
        'Flobberworm',
        'Voldemort',
        'Centaurs',
        'Quidditch',
        'Slytherin',
        'Boggart',
        'Tergeo',
        'Incendio',
        'Jelly-Legs Jinx',
        'Wingardium Leviosa',
        'Hagrid',
        'Gringotts',
        'Ollivanders',
        'Seeker',
        'Dumbledore',
        'Errol',
        'Ravenclaw',
        'Nimbus',
        'Nagini',
        'Accio',
        'Bludgers',
        'Bowtruckles',
        'Chaser',
        'Wand',
        'Winky',
        'Veritaserum',
        'Diagon Alley',
        'Expecto patronum',
        'Expelliarmus',
        'Fawkes',
        'Firebolt',
        'Gnomes',
        'Tarantallegra',
        'Scabbers',
        'Riddikulus',
        'Quaffle',
        'Keeper',
        'Lumos',
        'Obliviate',
        'Pensieve']
